# Generated by Django 5.2.3 on 2025-08-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('source', models.CharField(choices=[('SALARY', 'Зарплата'), ('BUSINESS', 'Бизнес'), ('GIFT', 'Подарок'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='Источник')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
            ],
        ),
    ]
