# Generated by Django 5.2.3 on 2025-08-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('category', models.CharField(choices=[('FOOD', 'Еда'), ('TRANSPORT', 'Транспорт'), ('HOUSING', 'Жилье'), ('ENTERTAINMENT', 'Развлечение'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='Категория')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'ordering': ['-data'],
            },
        ),
    ]
